// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luenemebbukitsyngntp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZW5lbWViYnVraXRzeW5nbnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzY2NzQsImV4cCI6MjA3MDk1MjY3NH0.0qZ68m85YbGnslRz1HKLrHdddKv8LvFqcnFJOa9wpco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});